# Delete all but the last x GitHub releases for certain packages.

name: 🚫　Delete Stale Releases
on:
  repository_dispatch:
    types: [released]
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wow-actions/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: wow-actions/delete-stale-releases@v1
        with:
          GITHUB_TOKEN: ${{ env.bot_token }}
          delete_tags: true
          keep_latest_count: 3
          group: '(?!^)@.*$'
          exclude: |
            @digiforce-cloud/x6@**
            @digiforce-cloud/x6-react@**
            @digiforce-cloud/x6-vue-shape@**
            @digiforce-cloud/x6-react-shape@**
            @digiforce-cloud/x6-angular-shape@**
            @digiforce-cloud/x6-react-components@**
